// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD5WN0uMIa-2cFD_HANgmV3A9QIyvK8fg',
    appId: '1:767229289165:web:e92c2e8994ec1051d9ff84',
    messagingSenderId: '767229289165',
    projectId: 'whatsapp-clone-flutter-cda1d',
    authDomain: 'whatsapp-clone-flutter-cda1d.firebaseapp.com',
    storageBucket: 'whatsapp-clone-flutter-cda1d.appspot.com',
    measurementId: 'G-XVQ36B6V5M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTWDCqiDQzoQokqXLacx-9gcZaDDG9Nnk',
    appId: '1:767229289165:android:2d2c7486236ec2efd9ff84',
    messagingSenderId: '767229289165',
    projectId: 'whatsapp-clone-flutter-cda1d',
    storageBucket: 'whatsapp-clone-flutter-cda1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-LmKI0S4aoiocDvNIlV6rmwuj5I8uNXI',
    appId: '1:767229289165:ios:436663bf609f2868d9ff84',
    messagingSenderId: '767229289165',
    projectId: 'whatsapp-clone-flutter-cda1d',
    storageBucket: 'whatsapp-clone-flutter-cda1d.appspot.com',
    iosClientId: '767229289165-vq53neevm2p92d8v2l9nnn09turekdi5.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappUi',
  );
}
